name: reminder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  flutter_timezone: ^4.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  timezone: ^0.10.1

  #dart run rename_app:main android="My App Name"
  rename_app: ^1.3.2

  #icon and splash generator
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.3

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    icon_background_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  
  #dart run change_app_package_name:main com.package.name
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true
