name: reminder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  flutter_timezone: ^4.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

  #dart run change_app_package_name:main com.package.name
  change_app_package_name: ^1.3.0

  #dart run rename_app:main android="App Name"
  rename_app: ^1.3.2

  # dart run icons_launcher:create
  icons_launcher: ^3.0.1

  # dart run flutter_native_splash:create
  flutter_native_splash: ^2.4.6

icons_launcher:
  image_path: "assets/ic_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: false
    web:
      enable: false
    macos:
      enable: false
    windows:
      enable: false
    linux:
      enable: false

flutter_native_splash:
  color: "#E9F2FF"
  image: assets/ic_splash.png
  android_12:
    image: assets/ic_splash.png
    icon_background_color: "#E9F2FF"

flutter:
  uses-material-design: true
  fonts:
    - family: Titilium Web SemiBold
      fonts:
        - asset: assets/fonts/Titilium.ttf
